config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]

  resources :pictures
  root "welcome#index"

  get '/login' => "sessions#login", as: "login"
  get '/logout' => "sessions#logout", as: "logout"
  post '/login' => "sessions#login_attempt"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt
  enum role: [:admin, :regular]
  mount_uploader :avatar, ImageUploader
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :encrypted_password, presence: true
  has_many :pictures
  has_many :relationships
  before_save :encrypt_password

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    if user && user.email == email && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def self.search(query)
    where("username ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ?", "#{query}%", "#{query}%", "#{query}%")
  end

  def encrypt_password
    if encrypted_password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(encrypted_password, salt)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:new, :create]
  before_action :save_login_state, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      @users = User.where(nil)
      if !params[:search].blank?
        @users = @users.search(params[:search][:query]) if !params[:search][:query].blank?
      end
      format.json
      format.html
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    @user = User.find_by_email(params[:user][:email])
    if @user.encrypted_password == params[:user][:encrypted_password]
      give_token
    else
      redirect_to home_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :bio, :encrypted_password, :email, :role, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label "Username" %>
      <%= form.text_field :username %>
    </div>

    <div class="form-group">
      <%= form.label "Email" %>
      <%= form.text_field :email %>
    </div>

    <div class="form-group">
      <%= form.label "Password" %>
      <%= form.password_field :encrypted_password %>
    </div>

    <div class="form-group">
      <%= form.label "First Name" %>
      <%= form.text_field :first_name %>
    </div>

    <div class="form-group">
      <%= form.label "Last Name" %>
      <%= form.text_field :last_name %>
    </div>

    <div class="form-group">
      <%= form.label "About Me" %>
      <%= form.text_area :bio, type: "text", rows: 3 %>
    </div>

    <div class="form-group">
      <%= form.label "Upload an avatar!" %>
      <%= form.file_field :avatar %>
    </div>

    <%= form.hidden_field :role, value: params[:role] %>

    <div class="form-group">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
  <div id="profile-info">
    <div class="row">
      <div class="profile-picture col-md-4"><%= image_tag @user.avatar.url || "default_profile_picture.jpg", style: "border-radius: 40px;", height: 200, width: 200, class: "img-fluid mx-auto d-block" %></div>
      <div class="col-md-4">
        <br><br>
        <div><%= @user.username %></div>
        <% 3.times do %><br><% end %>
        <div><%= "#{@user.first_name} #{@user.last_name}" %></div>
      </div>
      <div class="col-md-4">
        <br><br>
        <% if @current_user %>
          <% if @current_user.id == @user.id %>
            <div><%= button_to "Edit Profile", edit_user_path(@user.id), method: "get", class: "btn btn-primary btn-small" %></div>
          <% elsif !@current_user.relationships.find_by(followed_id: @user.id) %>
            <div><%= button_to "Follow", {controller: "relationships", action: "create", user_id: @current_user.id, followed_id: @user.id}, remote: true, class: "btn btn-primary btn-small" %></div>
          <% else %>
            <div><%= button_to "Unfollow", {controller: "relationships", action: "destroy", user_id: @current_user.id, followed_id: @user.id}, method: "delete", remote: true, data: {confirm: "Are you sure you want to unfollow?"}, class: "btn btn-primary btn-small" %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div id="user-photos">
    <div class="row">
      <% @user.pictures.each do |picture| %>
        <div class="card">
          <div class="card-header form-inline">
            <span><%= image_tag @user.avatar.url || "default_profile_picture.jpg", style: "border-radius: 40px", height: 40, width: 40 %></span>
            <span style="padding-left: 5px;">
              <div>
                <%= link_to "#{@user.username}", user_path(@user) %>
              </div>
              <div>
                <small class="text-muted"><%= link_to "#{picture.location.titleize}", {controller: "pictures", action: "index", location: picture.location} if picture.location %></small>
              </div>
            </span>
          </div>
          <a href="<%= picture_path(picture) %>"><%= image_tag picture.path.url, class: "img-fluid card-img-top" %></a>
          <div class="card-body">
            <p class="card-text"><%= picture.description %></p>
          </div>
          <div class="card-footer">
            <p class="card-text"><small class="text-muted"><%= "Uploaded at: #{picture.created_at.asctime}" %></small></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<style>
  #profile-info {
    padding: 10px;
    border-bottom-width: thin;
    border-bottom-style: groove;
    border-bottom-color: rgba(200, 200, 200, .5);
  }

  #user-photos {
    margin-top: 20px;
    padding: 10px;
  }

  .card {
    max-width: 25vw;
    margin: 10px;
  }
</style>