config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]

  resources :pictures
  root "welcome#index"

  get '/login' => "sessions#login", as: "login"
  get '/logout' => "sessions#logout", as: "logout"
  post '/login' => "sessions#login_attempt"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :path, ImageUploader

  def self.location_search(locations)
    where(location: locations)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.where(nil).order("created_at DESC")
    if !params[:search].blank? && !params[:search][:location].blank?
      url = "https://maps.googleapis.com/maps/api/place/textsearch/json?input=#{params[:search][:location]}&key=AIzaSyB3FXtpUa5MQ_rX_frJUEWx9hGJSwb0qJ4"
      response = open(url).read
      response_json = JSON.parse(response)
      location = response_json["results"][0]["geometry"]["location"]
      url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{location["lat"]},#{location["lng"]}&radius=1500&key=AIzaSyB3FXtpUa5MQ_rX_frJUEWx9hGJSwb0qJ4"
      response = open(url).read
      response_json = JSON.parse(response)

      locations = [params[:search][:location]]
      response_json["results"].each do |result|
        locations << result["name"]
      end
      @pictures = @pictures.location_search(locations).order("created_at DESC")
    elsif params[:location]
      @pictures = @pictures.location_search([params[:location]]).order("created_at DESC")
    end
    @pictures
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    if @current_user
      @picture = Picture.new
    else
      redirect_to root_path, notice: "Must be signed in to upload a picture!"
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:path, :description, :user_id, :likes, :location)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Upload your file!" %>
    <%= form.file_field :path %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <%= form.hidden_field :user_id, value: @current_user.id %>
  <%= form.hidden_field :likes, value: 0 %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="container">
  <div>
    <h3>See what other people are sharing!</h3>
  </div>
  <div>
    <% @pictures.each do |picture| %>
      <% user = User.find(picture.user_id) %>
      <div class="card">
        <div class="card-header form-inline">
          <span><%= image_tag user.avatar.url || "default_profile_picture.jpg", style: "border-radius: 40px", height: 40, width: 40 %></span>
          <span style="padding-left: 5px;">
            <div>
              <%= link_to "#{user.username}", user_path(user) %>
            </div>
            <div>
              <small class="text-muted"><%= link_to "#{picture.location.titleize}", {controller: "pictures", action: "index", location: picture.location} if picture.location %></small>
            </div>
          </span>
        </div>
        <a href="<%= picture_path(picture) %>"><%= image_tag picture.path.url, class: "img-fluid card-img-top" %></a>
        <div class="card-body">
          <p class="card-text"><%= picture.description %></p>
        </div>
        <div class="card-footer">
          <p class="card-text"><small class="text-muted"><%= "Uploaded at: #{picture.created_at.asctime}" %></small></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<style>
  .card {
    max-width: 40vw;
    margin-top: 20px;
    margin-bottom: 20px;
  }
</style>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<div class="container">
  <% user = User.find(@picture.user_id) %>
  <div class="card">
    <div class="card-header form-inline">
      <span><%= image_tag user.avatar.url || "default_profile_picture.jpg", style: "border-radius: 40px", height: 40, width: 40 %></span>
      <span style="padding-left: 5px;">
        <div>
          <%= link_to "#{user.username}", user_path(user) %>
        </div>
        <div>
          <small class="text-muted"><%= link_to "#{@picture.location.titleize}", {controller: "pictures", action: "index", location: @picture.location} if @picture.location %></small>
        </div>
      </span>
    </div>
    <%= image_tag @picture.path.url, class: "img-fluid card-img-top" %>
    <div class="card-body">
      <p class="card-text"><%= @picture.description %></p>
    </div>
    <div class="card-footer">
      <p class="card-text"><small class="text-muted"><%= "Uploaded at: #{@picture.created_at.asctime}" %></small></p>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>


<style>
  .card {
    max-width: 50vw;
    margin: 30px;
  }
</style>