config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]

  resources :pictures
  root "welcome#index"

  get '/login' => "sessions#login", as: "login"
  get '/logout' => "sessions#logout", as: "logout"
  post '/login' => "sessions#login_attempt"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NextFinalAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-light navbar-mint">
      <a class="navbar-brand" href="/">Imago</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/pictures">Discover<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= form_for :search, url: pictures_path, method: "get", class: "nav-item dropdown-item form-inline" do |form| %>
                <%= form.text_field :location, placeholder: "Search for pictures near your city!", style: "width: 300px;", class: "form-control mr-sm-1" %>
                <%= form.submit "Search", class: "btn btn-small" %>
              <% end %>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item form-inline">
            <%= button_to "Upload new picture!", new_picture_path, method: "get", style: "left: 20px;", class: "btn btn-small" if @current_user %>
          </li>
          <%= form_for :search, url: users_path, method: "get", html: {id: "search-form", class: "nav-item form-inline"} do |form| %>
            <%= form.text_field :query, placeholder: "Search for users!", style: "width: 300px;", list: "list", class: "form-control mr-sm-1" %>
            <datalist id="list"></datalist>
            <%= form.submit "Search", class: "btn btn-small" %>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item form-inline">
            <% if @current_user %>
              <a href="<%= user_path(@current_user) %>"><%= image_tag @current_user.avatar.url || "default_profile_picture.jpg", id: "current-user-profile-picture", style: "border-radius: 40px;", height: 40, width: 40 %></a>
              <%= content_tag :span, "#{@current_user.username}" %>
              <%= button_to "Sign Out", logout_path, class: "btn btn-sm", method: "get" %>
            <% else %>
              <%= button_to "Sign In", login_path, class: "btn btn-sm", method: "get" %>
              <%= button_to "Sign Up", new_user_path, class: "btn btn-sm", method: "get" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div id="flash">
      <% flash.each do |key, value| %>
      <div class="alert alert-secondary" role="alert"><%=h value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

<script>
  $(document).on("turbolinks:load", function() {
    $("#search_query").on("keyup", function(event) {
      event.preventDefault();

      if($(this).val() != "") {
        setTimeout(function () {
          $.ajax({
            method: "GET",
            url: "/users",
            data: $("#search_query").serialize(),
            dataType: "json",
            minimumInputLength: 2,
            success: function(data, status, jqXHR) {
              console.log(data);
              $("#list").html("");
              data.forEach(function(element) {
                let option = document.createElement("option");
                option.value = element.username;

                //append option to list
                $("#list").append(option);
              });
            },
            error: function() {
              console.log("Something went wrong");
            }
          });
        }, 1000);
      }
    });


  });
</script>

<style>
  .navbar-mint {
    background-color: #98ff98;
  }
</style>